[asset_hosts]
# URLs for hosting assets, defaults use the Panel server (--static-dirs) with
# relative URLs. These are used as {ASSET_...} variables in the rest of the
# configuration, and can be overridden with ASSET_... environment variables.
instructions         = "instructions"


[style]
# raw_css, css_files, logo, and favicon all support supplying URLs so style can
# be injected
raw_css              = ["css/geong.css"]
css_files            = []
logo                 = "images/geong_logo.png"
favicon              = "images/favicon.png"
header_color         = "#ffffff"
header_background    = "#00cc99"

    [style.colors]
    default          = "#00cc99"

    # Deep
    lobe             = "#ffea18"
    channel_fill     = "#fdc801"
    overbank         = "#b5cf6d"
    mtd              = "#6a5ca2"
    drape            = "#078cb1"

    # Shallow
    distributary_fluvial_channel_fill  = "#ffff00"
    upper_fan_delta_slope              = "#ffff00"
    upper_shoreface                    = "#ffff00"
    beach                              = "#ffff99"
    lower_shoreface                    = "#ffff99"
    mass_transport_deposits            = "#ffff99"
    tidal_channel_fill                 = "#ffff99"
    tidal_dunes_bars                   = "#ffff99"
    upper_delta_front                  = "#ffff99"
    floodplain_overbank                = "#f4b084"
    lower_delta_front                  = "#f4b084"
    lower_fan_delta_slope              = "#f4b084"
    offshore_transition                = "#f4b084"
    swamp_marsh                        = "#f4b084"
    tidal_flat                         = "#f4b084"
    bay_lagoon_lake                    = "#ccccff"
    deltaplain_overbank                = "#ccccff"
    offshore_fines                     = "#ccccff"
    prodelta                           = "#ccccff"

#
# Apps
#
[apps]
title            = "Geo:N:G"
apps             = ["deep", "shallow", "instructions"]
primary_app      = "deep"
reader           = "api"

    [apps.deep]
    label            = "Deep Marine"
    views            = ["workflow", "data_viewer"]
    primary_view     = "workflow"

        [apps.deep.workflow]
        label            = "Workflow"
        stages           = ["set_up", "composition", "filter_classes", "result", "report"]

        [apps.deep.data_viewer]
        label            = "Data Viewer"
        tables           = ["systems", "complexes", "elements"]
        page_size        = 20

            [apps.deep.data_viewer.columns]

                [apps.deep.data_viewer.columns.systems]
                smda_well_name                  = "SMDA Well Name"
                building_block_type             = "Building Block Type"
                unique_id                       = "Unique ID"
                descriptive_reservoir_quality   = "Reservoir Quality"
                thickness_mtvd                  = "Thickness Mtvd"
                top_depth_mtvd                  = "Top Depth Mtvd"
                base_depth_mtvd                 = "Base Depth Mtvd"
                ng_vsh40_pct                    = "Net Gross"
                conventional_facies_vs_hebs     = "Conventional Facies Vs Hebs"
                confinement                     = "Confinement"
                relative_dip_position           = "Relative Dip Position"
                relative_strike_position        = "Relative Strike Position"
                mean_phie_pct                   = "Mean Phie Pct"
                mean_phit_pct                   = "Mean Phit Pct"
                mean_k_md                       = "Mean K Md"
                mean_sw_pct                     = "Mean Sw Pct"

                [apps.deep.data_viewer.columns.complexes]
                smda_well_name                  = "SMDA Well Name"
                building_block_type             = "Building Block Type"
                unique_id                       = "Unique ID"
                descriptive_reservoir_quality   = "Reservoir Quality"
                parent_system_identifier        = "Parent System Identifier"
                thickness_mtvd                  = "Thickness Mtvd"
                top_depth_mtvd                  = "Top Depth Mtvd"
                base_depth_mtvd                 = "Base Depth Mtvd"
                ng_vsh40_pct                    = "Net Gross"
                conventional_facies_vs_hebs     = "Conventional Facies Vs Hebs"
                confinement                     = "Confinement"
                relative_dip_position           = "Relative Dip Position"
                relative_strike_position        = "Relative Strike Position"
                architectural_style             = "Architectural Style"
                mean_phie_pct                   = "Mean Phie Pct"
                mean_phit_pct                   = "Mean Phit Pct"
                mean_k_md                       = "Mean K Md"
                mean_sw_pct                     = "Mean Sw Pct"

                [apps.deep.data_viewer.columns.elements]
                smda_well_name                  = "SMDA Well Name"
                building_block_type             = "Building Block Type"
                unique_id                       = "Unique ID"
                descriptive_reservoir_quality   = "Reservoir Quality"
                parent_complex_identifier       = "Parent Complex Identifier"
                parent_system_identifier        = "Parent System Identifier"
                thickness_mtvd                  = "Thickness Mtvd"
                top_depth_mtvd                  = "Top Depth Mtvd"
                base_depth_mtvd                 = "Base Depth Mtvd"
                ng_vsh40_pct                    = "Net Gross"
                conventional_facies_vs_hebs     = "Conventional Facies Vs Hebs"
                confinement                     = "Confinement"
                relative_dip_position           = "Relative Dip Position"
                relative_strike_position        = "Relative Strike Position"
                spatial_position                = "Spatial Position"
                architectural_style             = "Architectural Style"
                mean_phie_pct                   = "Mean Phie Pct"
                mean_phit_pct                   = "Mean Phit Pct"
                mean_k_md                       = "Mean K Md"
                mean_sw_pct                     = "Mean Sw Pct"

    [apps.shallow]
    label            = "Shallow Marine"
    views            = ["workflow", "data_viewer"]
    primary_view     = "workflow"

        [apps.shallow.workflow]
        label            = "Workflow"
        stages           = ["set_up", "composition", "result", "report"]

        [apps.shallow.data_viewer]
        label            = "Data Viewer"
        tables           = ["systems", "complexes", "elements"]
        page_size        = 20

            [apps.shallow.data_viewer.columns]

                [apps.shallow.data_viewer.columns.systems]
                smda_well_name                  = "SMDA Well Name"
                building_block_type             = "Building Block Type"
                unique_id                       = "Unique ID"
                descriptive_reservoir_quality   = "Reservoir Quality"
                thickness_mtvd                  = "Thickness Mtvd"
                top_depth_mtvd                  = "Top Depth Mtvd"
                base_depth_mtvd                 = "Base Depth Mtvd"
                ng_vsh40_pct                    = "Net Gross"
                mean_phie_pct                   = "Mean Phie Pct"
                mean_phit_pct                   = "Mean Phit Pct"
                mean_k_md                       = "Mean K Md"
                mean_sw_pct                     = "Mean Sw Pct"

                [apps.shallow.data_viewer.columns.complexes]
                smda_well_name                  = "SMDA Well Name"
                building_block_type             = "Building Block Type"
                unique_id                       = "Unique ID"
                descriptive_reservoir_quality   = "Reservoir Quality"
                parent_system_identifier        = "Parent System Identifier"
                thickness_mtvd                  = "Thickness Mtvd"
                top_depth_mtvd                  = "Top Depth Mtvd"
                base_depth_mtvd                 = "Base Depth Mtvd"
                ng_vsh40_pct                    = "Net Gross"
                mean_phie_pct                   = "Mean Phie Pct"
                mean_phit_pct                   = "Mean Phit Pct"
                mean_k_md                       = "Mean K Md"
                mean_sw_pct                     = "Mean Sw Pct"

                [apps.shallow.data_viewer.columns.elements]
                smda_well_name                  = "SMDA Well Name"
                building_block_type             = "Building Block Type"
                unique_id                       = "Unique ID"
                descriptive_reservoir_quality   = "Reservoir Quality"
                parent_complex_identifier       = "Parent Complex Identifier"
                parent_system_identifier        = "Parent System Identifier"
                thickness_mtvd                  = "Thickness Mtvd"
                top_depth_mtvd                  = "Top Depth Mtvd"
                base_depth_mtvd                 = "Base Depth Mtvd"
                ng_vsh40_pct                    = "Net Gross"
                mean_phie_pct                   = "Mean Phie Pct"
                mean_phit_pct                   = "Mean Phit Pct"
                mean_k_md                       = "Mean K Md"
                mean_sw_pct                     = "Mean Sw Pct"

    [apps.instructions]
    label            = "Instructions"
    views            = ["net_to_gross", "deep", "shallow"]
    primary_view     = "net_to_gross"

        [apps.instructions.net_to_gross]
        label            = "Net to Gross Calculator"
        url              = "{ASSET_INSTRUCTIONS}/net_to_gross.md"

        [apps.instructions.deep]
        label            = "Deep Marine"
        url              = "{ASSET_INSTRUCTIONS}/deep.md"

        [apps.instructions.shallow]
        label            = "Shallow Marine"
        url              = "{ASSET_INSTRUCTIONS}/shallow.md"


#
# Stages
#
[stages]

    [stages.deep]

        [stages.deep.set_up]
        label            = "Set Up"

        [stages.deep.composition]
        label            = "Element Composition"

            [stages.deep.composition.warnings]
            not_100_text     = """
                The weights should equal **100%**.

                Currently, the weights sum to **{total:.0f}%**
                """

            [stages.deep.composition.params]
            ready_parameter  = "ready"

        [stages.deep.filter_classes]
        label            = "Lobe/Channel Filters"

        [stages.deep.result]
        label            = "Result"

            [stages.deep.result.params]
            ready_parameter  = "ready"
            auto_advance     = true

        [stages.deep.report]
        label            = "Final Report"
        report           = "net_gross_ppt"


    [stages.shallow]

        [stages.shallow.set_up]
        label            = "Set Up"

        [stages.shallow.composition]
        label            = "Element Composition"

            [stages.shallow.composition.warnings]
            no_elements_text = """
                No result. Your choices are not reflected in the underlying data
                and are considered geologically unlikely.

                Choose other another start point on the previous page or build a
                model using the customisation functionality above.
                """
            not_100_text     = """
                The weights should equal **100%**.

                Currently, the weights sum to **{total:.0f}%**
                """
            ng_above         = 90
            ng_above_text    = """
                Very high N:G values (~85-90% and above) are unlikely for an
                entire trap GRV unless strong observational or empirical evidence
                supports it.

                Consider sources of heterogeneity and build them in to your model
                with the appropriate elements and qualities.
                """

            [stages.shallow.composition.params]
            ready_parameter  = "sum_to_100"

        [stages.shallow.result]
        label            = "Result"

            [stages.shallow.result.params]
            ready_parameter  = "ready"
            auto_advance     = true

        [stages.shallow.report]
        label            = "Final Report"
        report           = "net_gross_ppt"


#
# Report specs
#
[report]

    [report.net_gross_ppt]
    generator = "powerpoint"
    template = "templates/geong_pptx.toml"
    file_name = "geong_{date:%Y%m%d}.pptx"

        [[report.net_gross_ppt.slide]]
        layout               = "title"
        title                = "Geo:N:G Report: {geox_id}"
        subtitle.type        = "text"
        subtitle.content     = "{date:%d %b %Y}"

        [[report.net_gross_ppt.slide]]
        layout               = "one_column"
        title                = "{geox_id} Scenarios"
        content.type         = "text"
        content.content      = "{scenario_list}"

        [[report.net_gross_ppt.slide]]
        nested.cfg           = "scenarios"
        nested.data          = "scenarios"

        [[report.net_gross_ppt.slide]]
        layout               = "closing"

        [report.net_gross_ppt.scenarios]
            [[report.net_gross_ppt.scenarios.slide]]
            layout               = "section"
            title                = "Scenario {scenario_name}"

            [[report.net_gross_ppt.scenarios.slide]]
            layout               = "test_content"
            title                = "Final estimate: {net_gross:.0f}%"
            chart.type           = "chart"
            chart.content        = "ref:composition"
            table.type           = "table"
            table.content        = "ref:composition"

            [report.net_gross_ppt.scenarios.content]

                [report.net_gross_ppt.scenarios.content.chart.composition]
                type                 = "bar_clustered"
                categories           = ["Lobe", "Channel Fill", "Overbank"]
                series_1             = [67, 27, 6]
                series_2             = [31, 55, 14]

                [report.net_gross_ppt.scenarios.content.table.composition]
                rows                 = 2
                cols                 = ["Building Block", "Weight", "N:G", "Contribution"]
