version: '3.4'

services:
  api:
    depends_on:
      - no-factor-auth
      - az
    environment:
      - AUTHORITY=http://no-factor-auth:8089/common/v2.0
      - STORAGE_URL=https://az:10000/devstoreaccount1
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/az.pem
      - CONTAINER=dls
      - FOLDER_NAME=data_dir
      - CLIENT_ID=
      - CLIENT_SECRET=
      - AUDIENCE=MY_AUDIENCE
      - LOG_USER_INFO=False
    volumes:
      - ./tests/ssl/az.pem:/etc/ssl/certs/az.pem
  tests:
    build: ./tests
    volumes:
      - ./tests/ssl/az.pem:/etc/ssl/certs/az.pem
    depends_on:
      - api
      - no-factor-auth
      - az
    environment:
      - FOLDER_NAME=data_dir
      - AUDIENCE=MY_AUDIENCE
      - API_ADDR=http://api:5000
      - AUTHORITY=http://no-factor-auth:8089/common
      - STORAGE_URL=https://az:10000/devstoreaccount1
    volumes:
      - ./tests/ssl/az.pem:/etc/ssl/certs/az.pem
  az:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    command: azurite-blob --blobHost 0.0.0.0 --oauth basic --loose --cert /tests/ssl/az.pem --key /tests/ssl/key.pem
    volumes:
      - ./tests/ssl:/tests/ssl
    ports:
      - 10000:10000
  no-factor-auth:
    image: lambdaville/no-factor-auth:v0.1.0
    environment:
      - TOKEN_ENDPOINT_ISSUER=https://sts.windows.net/
      - TOKEN_ENDPOINT_AUDIENCE=https://storage.azure.com
      - TOKEN_ENDPOINT_SUBJECT=https://storage.azure.com
    ports:
      - 8089:8089
  oauth2-proxy:
    environment:
      - OAUTH2_PROXY_CLIENT_ID=id
      - OAUTH2_PROXY_CLIENT_SECRET=secret
      - OAUTH2_PROXY_COOKIE_SECRET=abcdefghijklmnop
      - OAUTH2_PROXY_OIDC_ISSUER_URL=http://no-factor-auth:8089/common/v2.0
