template         = "geong.pptx"

[layouts]
title                    = "Title Slide"
section                  = "Title Only"
one_column               = "Title and Content"
table                    = "Table"
chart                    = "Chart"
chart_table              = "Chart and Table"
closing                  = "Blank"


[placeholders]

    [placeholders.title]
    subtitle                       = 1

    [placeholders.one_column]
    content                        = 1

    [placeholders.section]
    subtitle                       = 1

    [placeholders.table]
    table                          = 13

    [placeholders.chart]
    chart                          = 14

    [placeholders.chart_table]
    chart                          = 13
    table                          = 14

    [placeholders.closing]
    presenter                      = 1
