[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"


[tool.black]
line-length = 88


[tool.pytest.ini_options]
markers = [
    "selenium: tests using selenium (deselect with '-m \"not selenium\"')"
]
