name: deploy
on:
  push:
    tags:
       - '*'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and tag docker images
        run: |
          export TAG=`git describe --tags`
          docker-compose build
      - name: Push to GitHub Container Registry
        run: |
          export TAG=`git describe --tags`
          docker-compose push app api
