name: integration
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: run integration tests
        run: |
          docker-compose -f docker-compose.yml -f docker-compose-test.yml build
          docker-compose -f docker-compose.yml -f docker-compose-test.yml up --exit-code-from tests
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and tag docker images
        run: |
          export TAG=`git describe --tags`
          docker-compose build
      - name: Push to GitHub Container Registry
        run: |
          export TAG=`git describe --tags`
          docker-compose push app api
